using System;
using System.Threading.Tasks;
using System.Drawing;
using System.Collections.Generic;

using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.FormKeys.SkyrimSE;
using System.Linq;

namespace SynStandardLightingTemplate
{
    public class Settings
    {
        public byte Color = 25;
        public List<string> IgnoredCells = [
            "WindhelmPalaceUpstairs01",
            "WindhelmPalaceUpstairs02",
        ];
    }
    internal class Program
    {
        public static Lazy<Settings>? LazySettings;
        public static Settings Config => LazySettings!.Value;
        public static Color ColorSet;
        public static CellLighting.Inherit cl = CellLighting.Inherit.AmbientColor | CellLighting.Inherit.DirectionalColor | CellLighting.Inherit.FogColor |
                    CellLighting.Inherit.FogNear | CellLighting.Inherit.FogFar | CellLighting.Inherit.DirectionalRotation | CellLighting.Inherit.DirectionalFade |
                    CellLighting.Inherit.ClipDistance | CellLighting.Inherit.FogPower | CellLighting.Inherit.FogMax | CellLighting.Inherit.LightFadeDistances;
        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .SetAutogeneratedSettings<Settings>("Color Settings", "Colors.json", out LazySettings, false)
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, "SynSLT.esp")
                .Run(args);
        }
        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            ColorSet = Color.FromArgb(Config.Color, Config.Color, Config.Color);
            foreach (var lt in state.LoadOrder.PriorityOrder.LightingTemplate().WinningContextOverrides())
            {
                Console.WriteLine($"Patching LIGHTING TEMPLATE {lt.Record.EditorID}");
                var nlt = lt.GetOrAddAsOverride(state.PatchMod);
                nlt.DirectionalRotationZ = 0;
                nlt.DirectionalRotationXY = 0;
                nlt.FogNear = 0;
                nlt.FogFar = 0;
                nlt.DirectionalFade = 0;
                nlt.FogPower = 1;
                nlt.FogMax = 1;
                nlt.FogClipDistance = 0;
                nlt.LightFadeEndDistance = 41000;
                nlt.LightFadeStartDistance = 30000;
                nlt.AmbientColor = ColorSet;
                nlt.DirectionalColor = ColorSet;
                nlt.FogNearColor = ColorSet;
                nlt.FogFarColor = ColorSet;
                nlt.AmbientColors = new()
                {
                    Scale = 0,
                    Specular = ColorSet,
                    DirectionalXMinus = ColorSet,
                    DirectionalXPlus = ColorSet,
                    DirectionalYMinus = ColorSet,
                    DirectionalYPlus = ColorSet,
                    DirectionalZMinus = ColorSet,
                    DirectionalZPlus = ColorSet,
                };
                nlt.DirectionalAmbientColors = new()
                {
                    Scale = 0,
                    Specular = ColorSet,
                    DirectionalXMinus = ColorSet,
                    DirectionalXPlus = ColorSet,
                    DirectionalYMinus = ColorSet,
                    DirectionalYPlus = ColorSet,
                    DirectionalZMinus = ColorSet,
                    DirectionalZPlus = ColorSet,
                };
            }
            foreach (var cel in state.LoadOrder.PriorityOrder.Cell().WinningContextOverrides(state.LinkCache))
            {
                if (cel != null && cel.Record != null && cel.Record.FormKey != null)
                {
                    var mtx = state.LinkCache.ResolveAllContexts<ICell, ICellGetter>(cel.Record.FormKey);
                    var cell = mtx.Last(x => !x.Record.MajorFlags.HasFlag((Cell.MajorFlag)0x1000));
                    if (cell.Record != null && cell.Record.Lighting != null && (cell.Record.LightingTemplate.IsNull || cell.Record.Lighting.Inherits != cl) && !Config.IgnoredCells.Contains(cell.Record.EditorID ?? ""))
                    {
                        var nc = cell.GetOrAddAsOverride(state.PatchMod);
                        Console.WriteLine($"Patching CELL {nc.Name?.ToString() ?? nc.EditorID?.ToString()}");
                        if (nc.LightingTemplate.IsNull)
                        {
                            nc.LightingTemplate.SetTo(Skyrim.LightingTemplate.DefaultLightingTemplate);
                        }
                        if (nc.Lighting != null && nc.Lighting.Inherits != cl)
                        {
                            nc.Lighting.Inherits = cl;
                        }
                    }
                }
            }
            //Blackreach weather
            var nw = state.PatchMod.Weathers.GetOrAddAsOverride(Skyrim.Weather.BlackreachWeather.Resolve(state.LinkCache));
            nw.EffectLightingColor = new()
            {
                Sunrise = ColorSet,
                Day = ColorSet,
                Sunset = ColorSet,
                Night = ColorSet,
            };
            nw.FogNearColor = new()
            {
                Sunrise = ColorSet,
                Day = ColorSet,
                Sunset = ColorSet,
                Night = ColorSet,
            };
            nw.FogFarColor = new()
            {
                Sunrise = ColorSet,
                Day = ColorSet,
                Sunset = ColorSet,
                Night = ColorSet,
            };
            nw.WaterMultiplierColor = new()
            {
                Sunrise = ColorSet,
                Day = ColorSet,
                Sunset = ColorSet,
                Night = ColorSet,
            };
            nw.FogDistanceDayFar = 0;
            nw.FogDistanceDayNear = 0;
            nw.FogDistanceNightFar = 0;
            nw.FogDistanceNightNear = 0;
            nw.FogDistanceDayPower = 0;
            nw.FogDistanceNightPower = 0;
            nw.FogDistanceNightMax = 0;
            nw.FogDistanceDayMax = 0;
            nw.ThunderLightningFrequency = new(0.0);
            nw.PrecipitationBeginFadeIn = new(0.0);
            nw.PrecipitationEndFadeOut = new(0.0);
            nw.DirectionalAmbientLightingColors = new()
            {
                Sunrise = {
                    DirectionalXMinus = ColorSet,
                    DirectionalXPlus = ColorSet,
                    DirectionalYMinus = ColorSet,
                    DirectionalYPlus = ColorSet,
                    DirectionalZMinus = ColorSet,
                    DirectionalZPlus = ColorSet,
                    Specular = Color.FromArgb(0, 0, 0),
                    Scale = 0,
                },
                Day = {
                    DirectionalXMinus = ColorSet,
                    DirectionalXPlus = ColorSet,
                    DirectionalYMinus = ColorSet,
                    DirectionalYPlus = ColorSet,
                    DirectionalZMinus = ColorSet,
                    DirectionalZPlus = ColorSet,
                    Specular = Color.FromArgb(0, 0, 0),
                    Scale = 0,
                },
                Sunset = {
                    DirectionalXMinus = ColorSet,
                    DirectionalXPlus = ColorSet,
                    DirectionalYMinus = ColorSet,
                    DirectionalYPlus = ColorSet,
                    DirectionalZMinus = ColorSet,
                    DirectionalZPlus = ColorSet,
                    Specular = Color.FromArgb(0, 0, 0),
                    Scale = 0,
                },
                Night = {
                    DirectionalXMinus = ColorSet,
                    DirectionalXPlus = ColorSet,
                    DirectionalYMinus = ColorSet,
                    DirectionalYPlus = ColorSet,
                    DirectionalZMinus = ColorSet,
                    DirectionalZPlus = ColorSet,
                    Specular = Color.FromArgb(0, 0, 0),
                    Scale = 0,
                }
            };
        }
    }
}