using System;
using System.Drawing;
using System.Collections.Generic;
using System.Threading.Tasks;

using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.FormKeys.SkyrimSE;
using Noggog;

namespace SynPatcher
{
    public class Settings
    {
        public byte Brightness = 25;
        public List<string> IgnoredCells = [
            "WindhelmPalaceUpstairs01",
            "WindhelmPalaceUpstairs02",
        ];
    }
    class Program
    {
        public static Lazy<Settings>? LazySettings;
        public static Settings Config => LazySettings!.Value;
        public static Color ColorSet;
        public static CellLighting.Inherit cl = CellLighting.Inherit.AmbientColor | CellLighting.Inherit.DirectionalColor | CellLighting.Inherit.FogColor |
                    CellLighting.Inherit.FogNear | CellLighting.Inherit.FogFar | CellLighting.Inherit.DirectionalRotation | CellLighting.Inherit.DirectionalFade |
                    CellLighting.Inherit.ClipDistance | CellLighting.Inherit.FogPower | CellLighting.Inherit.FogMax | CellLighting.Inherit.LightFadeDistances;
        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .SetAutogeneratedSettings("Color Settings", "Colors.json", out LazySettings, false)
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, "SynSLT.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            ColorSet = Color.FromArgb(Config.Brightness, Config.Brightness, Config.Brightness);
            foreach (var lt in state.LoadOrder.PriorityOrder.LightingTemplate().WinningContextOverrides())
            {
                var nlt = lt.GetOrAddAsOverride(state.PatchMod);
                nlt.DirectionalRotationXY = 0;
                nlt.DirectionalRotationZ = 90;
                nlt.DirectionalFade = 0;
                nlt.DirectionalColor = ColorSet;
                nlt.LightFadeStartDistance = 4000;
                nlt.LightFadeEndDistance = 5000;
                nlt.FogPower = 1;
                nlt.FogMax = 1;
                nlt.FogNear = 600;
                nlt.FogFar = 10000;
                nlt.FogClipDistance = 6000;
                nlt.FogNearColor = Color.FromArgb(0, 0, 0);
                nlt.FogFarColor = Color.FromArgb(0, 0, 0);
                nlt.AmbientColor = ColorSet;
                nlt.AmbientColors = new()
                {
                    Scale = 0,
                    Specular = Color.FromArgb(0, 0, 0),
                    DirectionalXMinus = ColorSet,
                    DirectionalXPlus = ColorSet,
                    DirectionalYMinus = ColorSet,
                    DirectionalYPlus = ColorSet,
                    DirectionalZMinus = ColorSet,
                    DirectionalZPlus = ColorSet,
                };
                nlt.DirectionalAmbientColors = new()
                {
                    Scale = 0,
                    Specular = Color.FromArgb(0, 0, 0),
                    DirectionalXMinus = ColorSet,
                    DirectionalXPlus = ColorSet,
                    DirectionalYMinus = ColorSet,
                    DirectionalYPlus = ColorSet,
                    DirectionalZMinus = ColorSet,
                    DirectionalZPlus = ColorSet,
                };
            }
            state.LoadOrder.PriorityOrder.Cell().WinningContextOverrides(state.LinkCache).ForEach(ctx =>
            {
                if (ctx != null && ctx.Record != null && ctx.Record.FormKey != null && !Config.IgnoredCells.Contains(ctx.Record.EditorID ?? ""))
                {
                    var nc = ctx.GetOrAddAsOverride(state.PatchMod);
                    if (nc.LightingTemplate.IsNull)
                    {
                        nc.LightingTemplate.SetTo(Skyrim.LightingTemplate.DefaultLightingTemplate);
                    }
                    if (nc.Lighting != null)
                    {
                        nc.Lighting.Inherits = cl;
                        nc.Lighting.AmbientColor = ColorSet;
                        nc.Lighting.AmbientColors = new()
                        {
                            DirectionalXMinus = ColorSet,
                            DirectionalXPlus = ColorSet,
                            DirectionalYMinus = ColorSet,
                            DirectionalYPlus = ColorSet,
                            DirectionalZMinus = ColorSet,
                            DirectionalZPlus = ColorSet,
                        };
                        nc.Lighting.DirectionalColor = ColorSet;
                        nc.Lighting.DirectionalRotationXY = 0;
                        nc.Lighting.DirectionalRotationZ = 90;
                        nc.Lighting.DirectionalFade = 0;
                        nc.Lighting.FogFarColor = Color.FromArgb(0, 0, 0);
                        nc.Lighting.FogNearColor = Color.FromArgb(0, 0, 0);
                        nc.Lighting.FogClipDistance = 6000;
                        nc.Lighting.FogNear = 600;
                        nc.Lighting.FogFar = 10000;
                        nc.Lighting.FogPower = 1;
                        nc.Lighting.FogMax = 1;
                        nc.Lighting.LightFadeBegin = 4000;
                        nc.Lighting.LightFadeEnd = 5000;
                    }
                }
            });
            //Blackreach weather
            var nw = state.PatchMod.Weathers.GetOrAddAsOverride(Skyrim.Weather.BlackreachWeather.Resolve(state.LinkCache));
            nw.EffectLightingColor = new()
            {
                Sunrise = ColorSet,
                Day = ColorSet,
                Sunset = ColorSet,
                Night = ColorSet,
            };
            nw.FogNearColor = new()
            {
                Sunrise = ColorSet,
                Day = ColorSet,
                Sunset = ColorSet,
                Night = ColorSet,
            };
            nw.FogFarColor = new()
            {
                Sunrise = ColorSet,
                Day = ColorSet,
                Sunset = ColorSet,
                Night = ColorSet,
            };
            nw.WaterMultiplierColor = new()
            {
                Sunrise = ColorSet,
                Day = ColorSet,
                Sunset = ColorSet,
                Night = ColorSet,
            };
            nw.FogDistanceDayFar = 0;
            nw.FogDistanceDayNear = 0;
            nw.FogDistanceNightFar = 0;
            nw.FogDistanceNightNear = 0;
            nw.FogDistanceDayPower = 0;
            nw.FogDistanceNightPower = 0;
            nw.FogDistanceNightMax = 0;
            nw.FogDistanceDayMax = 0;
            nw.ThunderLightningFrequency = new(0.0);
            nw.PrecipitationBeginFadeIn = new(0.0);
            nw.PrecipitationEndFadeOut = new(0.0);
            nw.DirectionalAmbientLightingColors = new()
            {
                Sunrise = {
                    DirectionalXMinus = ColorSet,
                    DirectionalXPlus = ColorSet,
                    DirectionalYMinus = ColorSet,
                    DirectionalYPlus = ColorSet,
                    DirectionalZMinus = ColorSet,
                    DirectionalZPlus = ColorSet,
                    Specular = Color.FromArgb(0, 0, 0),
                    Scale = 0,
                },
                Day = {
                    DirectionalXMinus = ColorSet,
                    DirectionalXPlus = ColorSet,
                    DirectionalYMinus = ColorSet,
                    DirectionalYPlus = ColorSet,
                    DirectionalZMinus = ColorSet,
                    DirectionalZPlus = ColorSet,
                    Specular = Color.FromArgb(0, 0, 0),
                    Scale = 0,
                },
                Sunset = {
                    DirectionalXMinus = ColorSet,
                    DirectionalXPlus = ColorSet,
                    DirectionalYMinus = ColorSet,
                    DirectionalYPlus = ColorSet,
                    DirectionalZMinus = ColorSet,
                    DirectionalZPlus = ColorSet,
                    Specular = Color.FromArgb(0, 0, 0),
                    Scale = 0,
                },
                Night = {
                    DirectionalXMinus = ColorSet,
                    DirectionalXPlus = ColorSet,
                    DirectionalYMinus = ColorSet,
                    DirectionalYPlus = ColorSet,
                    DirectionalZMinus = ColorSet,
                    DirectionalZPlus = ColorSet,
                    Specular = Color.FromArgb(0, 0, 0),
                    Scale = 0,
                }
            };
        }
    }
}